### PR TITLE
fix #218 iam__enum_users is not adding users to database

### LINKED ISSUE #218: Module iam__enum_users is not adding users to database
After running the module `iam__enum_users` successfully, and finding at least one user, the user(s) aren't being added to the database. `data IAM` returns the below.

```
 > data IAM
{
  "Users": []
}

```

### PR DESCRIPTION
**Pull request by naikordian**
iam__enum_roles has a similar bug as well, I will it fix later

### CODE REVIEW

**Comment by RyanJarv** [comment]
Thanks for the PR! We should be able to take a look at this sometime this week.

**Review by RyanJarv — CHANGES_REQUESTED** [review]
Hey, looks good. I ran into a few issues when testing this, however for the most part that's not related to this PR and I can fix that elsewhere.

One thing I did notice though is the user structure doesn't match what's used in other modules. Made a suggestion that fixes that, if that looks good to you we can get this merged.

**Comment by naikordian** [comment]
I will fix  #257  later if this PR passes review.

**Review by RyanJarv — APPROVED** [review]
lgtm

**Pull request merged**
